language: "en"
reviews:
  enabled: true
  summary: true
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "Draft"
  path_filters:
    - "!**/*.min.js"
    - "!**/*.bundle.js"
    - "!**/dist/**"
    - "!**/node_modules/**"
  max_comments: 25
